//
//  FeedShowPresenter.swift
//  PLinkInstagramDemo
//
//  Created by msm72 on 05.09.17.
//  Copyright (c) 2017 RemoteJob. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - Presentation Logic protocols
protocol FeedShowPresentationLogic {
    func prepareToDisplayFeedComment(fromResponseModel responseModel: FeedShowModels.Feed.ResponseModel)
}

class FeedShowPresenter: FeedShowPresentationLogic {
    // MARK: - Properties
    weak var viewController: FeedShowDisplayLogic?
    
    
    // MARK: - Presentation Logic implementation
    func prepareToDisplayFeedComment(fromResponseModel responseModel: FeedShowModels.Feed.ResponseModel) {
        let viewModel = FeedShowModels.Feed.ViewModel(feedDisplayed: responseModel.feedDisplayed)
        viewController?.displayFeed(fromViewModel: viewModel)
    }
}
