//
//  FeedsShowRouter.swift
//  PLinkInstagramDemo
//
//  Created by msm72 on 01.09.17.
//  Copyright (c) 2017 RemoteJob. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - Input & Output protocols
@objc protocol FeedsShowRoutingLogic {
    //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol FeedsShowDataPassing {
    var dataStore: FeedsShowDataStore? { get }
}

class FeedsShowRouter: NSObject, FeedsShowRoutingLogic, FeedsShowDataPassing {
    // MARK: - Properties
    weak var viewController: FeedsShowViewController?
    var dataStore: FeedsShowDataStore?
    
    
    // MARK: - Routing
    //func routeToSomewhere(segue: UIStoryboardSegue?) {
    //  if let segue = segue {
    //    let destinationVC = segue.destination as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //  } else {
    //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
    //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //    navigateToSomewhere(source: viewController!, destination: destinationVC)
    //  }
    //}
    
    
    // MARK: - Navigation
    //func navigateToSomewhere(source: FeedsShowViewController, destination: SomewhereViewController) {
    //  source.show(destination, sender: nil)
    //}
    
    
    // MARK: - Passing data
    //func passDataToSomewhere(source: FeedsShowDataStore, destination: inout SomewhereDataStore) {
    //  destination.name = source.name
    //}
}
