//
//  FeedsShowPresenter.swift
//  PLinkInstagramDemo
//
//  Created by msm72 on 01.09.17.
//  Copyright (c) 2017 RemoteJob. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - Presentation Logic protocols
protocol FeedsShowPresentationLogic {
    func presentSomething(response: FeedsShowModels.Something.ResponseModel)
}

class FeedsShowPresenter: FeedsShowPresentationLogic {
    // MARK: - Properties
    weak var viewController: FeedsShowDisplayLogic?
    
    
    // MARK: - Presentation Logic implementation
    func presentSomething(response: FeedsShowModels.Something.ResponseModel) {
        let viewModel = FeedsShowModels.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
