//
//  FeedsShowRouter.swift
//  PLinkInstagramDemo
//
//  Created by msm72 on 01.09.17.
//  Copyright (c) 2017 RemoteJob. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - Input & Output protocols
@objc protocol FeedsShowRoutingLogic {
    func transitionToFeedShowScene()
}

protocol FeedsShowDataPassing {
    var dataStore: FeedsShowDataStore? { get set }
}

class FeedsShowRouter: NSObject, FeedsShowRoutingLogic, FeedsShowDataPassing {
    // MARK: - Properties
    weak var viewController: FeedsShowViewController?
    var dataStore: FeedsShowDataStore?
    
    
    // MARK: - Routing
    func transitionToFeedShowScene() {
        let storyboard = UIStoryboard(name: "FeedShow", bundle: nil)
        let destinationVC = storyboard.instantiateViewController(withIdentifier: "FeedShowVC") as! FeedShowViewController
        var destinationDS = destinationVC.router!.dataStore!
        
        dataPassToFeedShowScene(source: dataStore!, destination: &destinationDS)
        navigateToFeedShowScene(fromSource: viewController!, toDestination: destinationVC)
    }
    
    
    // MARK: - Navigation
    func navigateToFeedShowScene(fromSource source: FeedsShowViewController, toDestination destination: FeedShowViewController) {
        source.navigationController?.pushViewController(destination, animated: true)
//        show(destination, sender: nil)
    }
    
    
    // MARK: - Passing data
    func dataPassToFeedShowScene(source: FeedsShowDataStore, destination: inout FeedShowDataStore) {
        destination.feed = source.feedSelected
    }
}
