//
//  FeedsShowPresenter.swift
//  PLinkInstagramDemo
//
//  Created by msm72 on 01.09.17.
//  Copyright (c) 2017 RemoteJob. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - Presentation Logic protocols
protocol FeedsShowPresentationLogic {
    func prepareFeedsToDisplay(fromResponseModel responseModel: FeedsShowModels.Feeds.ResponseModel)
}

class FeedsShowPresenter: FeedsShowPresentationLogic {
    // MARK: - Properties
    weak var viewController: FeedsShowDisplayLogic?
    
    
    // MARK: - Presentation Logic implementation
    func prepareFeedsToDisplay(fromResponseModel responseModel: FeedsShowModels.Feeds.ResponseModel) {
        let viewModel = FeedsShowModels.Feeds.ViewModel(feeds: responseModel.feeds)
        viewController?.feedsDisplay(fromViewModel: viewModel)
    }
}
